[project]
name = "leetcode"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "numpy==1.26.4",
    "pandas==2.2.2",
    "sortedcontainers>=2.4.0",
]
